title: Óscar Córdova &middot; Full Stack Engineer
logo:  "logo.svg" # you can add own logo.
description: Full Stack Engineer based in Mexico City, experienced in both front-end and back-end development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ocordova.me" # the base hostname & protocol for your site, e.g. http://example.com


# Author Settings
author:
  name: Óscar Córdova
  image: '/assets/img/profile.jpg'
  job: Full Stack Engineer
  bio: 
  email: hola@ocordova.me


# Contact links
contact:
  - name: GitHub
    link: https://github.com/ocordova
  - name: Twitter
    link: https://twitter.com/ocordova
  - name: Instagram
    link: https://instagram.com/ocordova
  - name: Telegram
    link: https://telegram.me/oscordova

# Comment Section (Disqus)
disqus-identifier: # add your shortname for Disqus Comment.


# Google Analytics
google-analytics: UA-16434715-1 # add your identifier. For example UA-99631805-1.


# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll/tagging

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag-page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed


# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
