title: Óscar Córdova &middot; Full Stack Engineer
logo:  "logo.svg" # you can add own logo.
description: Full Stack Engineer based in Mexico City, experienced in both front-end and back-end development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ocordova.me" # the base hostname & protocol for your site, e.g. http://example.com


#Author
author: Óscar Córdova

# SEO
twitter:
  username: ocordova
  card: summary

# Google Analytics
google-analytics: UA-16434715-1 # add your identifier. For example UA-99631805-1.

# Feed
feed:
  path: feed.xml

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-minifier
  - jekyll-feed

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages


# Exclude from processing.
exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - vendor
  - package-lock.json
  - package.json
  - postcss.config.js
  - README.md
  - tailwind.config.js
